library(dplyr)
library(ggplot2)
library(shiny)
library(tidyr)
library(rsconnect)
source("graph_making_shiny.R")

server <- function(input, output) {
  output$ass1 <- renderPlot(graph_ass1)
  output$ass2 <- renderPlot(graph_ass2)
  output$ass3 <- renderPlot(graph_ass3)
  output$cunt1 <- renderPlot(graph_cunt1)
  output$cunt2 <- renderPlot(graph_cunt2)
  output$cunt3 <- renderPlot(graph_cunt3)
  output$dick1 <- renderPlot(graph_dick1)
  output$dick2 <- renderPlot(graph_dick2)
  output$dick3 <- renderPlot(graph_dick3)
  output$fuck1 <- renderPlot(graph_fuck1)
  output$fuck2 <- renderPlot(graph_fuck2)
  output$fuck3 <- renderPlot(graph_fuck3)
  output$tits1 <- renderPlot(graph_tit1)
  output$tits2 <- renderPlot(graph_tit2)
  output$tits3 <- renderPlot(graph_tit3)
}
